### PR TITLE
Avoid the "Neither 'source' nor 'contents' nor 'contents_pillar' nor 'co...

### PR DESCRIPTION
**Pull request by shawnbutts**
...ntents_grains' was defined, yet 'replace' was set to 'True'." Warning

i don't understand why you'd want to deal with the same file in two different places anyway.

### CODE REVIEW

**Comment by nmadhok** [comment]
@shawnbutts I don't think so this is the way to do it.

**Comment by shawnbutts** [comment]
It seems to work in my testing.  @nmadhok do you have any suggestions?

**Comment by nmadhok** [comment]
@shawnbutts Did you encounter any problem or errors when running the original code before making changes?

**Comment by babilen** [comment]
The original code should, and does, work. We use it in production in a variety of systems. What were your actual problems @shawnbutts ?

**Comment by shawnbutts** [comment]
I agree, it should work without my changes and the error is most likely a bug in Salt.

What version of Salt do you use?  When using this formula without these changes with 2014.7.1 I get the following error.

"Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is 'no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily"

In any case, isn't it cleaner to manage {{ users.sudoers_dir }}/{{ name }} once in one section of the cold?  What is the benefit to managing file permissions (line 172-177) and file contents (194-200) separately in the original code?

**Comment by nmadhok** [comment]
@shawnbutts Is that appearing as an Error or a warning? Can you take a screenshot of the state run and the message and attach it here?

**Comment by shawnbutts** [comment]
Sorry, it was a Warning and not an Error.  I no longer have the output as I haven't had it happen since I deployed this PR in my environment.  I also don't have a ready environment to run the pre-PR code in at the moment.

**Comment by nmadhok** [comment]
@shawnbutts I will try to test this formula soon. I had been little busy with the SaltConf but hopefully I will be able to test this next week and submit an appropriate fix. I'm closing this PR for now since it's just a warning and not an Error but If it seems to me that your fix is relevant then I'll reopen it and Merge!

**Pull request closed without merging**
