### PR TITLE
(Re-)enable pillar users:_lookup

### PR DESCRIPTION
**Pull request by alxwr**
Could not use pillar `users:lookup`. Implemented `users:_lookup` which is ignored when iterating through user names.

### CODE REVIEW

**Comment by aboe76** [comment]
@alxwr why couldn't you use ```users:lookup```?

**Comment by alxwr** [comment]
@aboe76 because

```
users:
  lookup:
    # stuff
```

Tries to create/manage a user named `lookup`. :-)

**Comment by aboe76** [comment]
@alxwr, now I understand but why not ignore lookup and create _lookup...

**Comment by alxwr** [comment]
@aboe76 So there could be a user named `lookup`. :-)
It's a matter of style or preference really. I normally name meta parameters in YAML structures starting with a '_' to indicate they're meta.

https://xkcd.com/917/ (Sry, couldn't resist.)

**Comment by aboe76** [comment]
@alxwr lol, before we merge this I would like some more input on this one..because it differs from the other formula's.. @puneetk or @0xf10e can you take a look?

**Comment by alxwr** [comment]
@aboe76 I've got no problem with changing it back to `loopback` tough. :-) (Just thought it would prevent an edge-case.)

**Comment by 0xf10e** [comment]
The lookup data sure won't have subkeys like those used for normal user's attributes (password, shell, …). We could add checks for those via `test.check_pillar` instead.

**Comment by alxwr** [comment]
@0xf10e Good idea! But then we can't have both, a user `lookup` _and_ a modification of `map.jinja`. I'm more for the explicit way: Either `lookup` is (conceptually) a user or it isn't.

IMHO the pillar structure lacks separation between various kinds of data (here: OS specifics and user accounts).
If we just started this formula, I'd propose the following change, but I'm well aware that this is a breaking change now, so I'm against it. (Although one could write a compatibility layer.)

```
users:
  lookup:
    # stuff
  definitions:  # or 'users' or 'accounts or ...
   # actual definitions of user account settings
```

@0xf10e @aboe76 
I can't decide on the importance of `users:lookup` (meaning that it _must_ be used for `map.jinja`). In my use case it just does not matter. But I don't know about yours. :-) So please tell me whether to remove that `_` from `_lookup`, or to implement the `test.check_pillar` workaround. :-)

Thanks!

**Comment by 0xf10e** [comment]
How about putting things configure the formula into `[users-formula]` then?
Keeps it out of the list of users entirely. 

Am 8. Juli 2017 09:28:10 MESZ schrieb alxwr <notifications@github.com>:
> @0xf10e Good idea! But then we can't have both, a user `lookup` _and_
> a modification of `map.jinja`. I'm more for the explicit way: Either
> `lookup` is (conceptually) a user or it isn't.
> 
> IMHO the pillar structure lacks separation between various kinds of
> data (here: OS specifics and user accounts).
> If we just started this formula, I'd propose the following change, but
> I'm well aware that this is a breaking change now, so I'm against it.
> (Although one could write a compatibility layer.)
> 
> ```
> users:
>   lookup:
>     # stuff
>   definitions:  # or 'users' or 'accounts or ...
>    # actual definitions of user account settings
> ```
> 
> @0xf10e @aboe76 
> I can't decide on the importance of `users:lookup` (meaning that it
> _must_ be used for `map.jinja`). In my use case it just does not
> matter. But I don't know about yours. :-) So please tell me whether to
> remove that `_` from `_lookup`, or to implement the
> `test.check_pillar` workaround. :-)
> 
> Thanks!

**Comment by alxwr** [comment]
@0xf10e you mean like

```yaml
users:
  # user definitions
users_formula:
  lookup:
    # stuff
```
?

LGTM. Clear separation.
Can I start to implement it, or are there any vetos? :)

**Comment by 0xf10e** [comment]
I think I would go with `users-formula` like it's `zabbix-agent` in the zabbix-formula (where I thought I had seen the usage of the pillar-key `zabbix-formula`…).

Am 10. Juli 2017 08:29:25 MESZ schrieb alxwr <notifications@github.com>:
> @0xf10e you mean like
> 
> ```yaml
> users:
>   # user definitions
> users_formula:
>   lookup:
>     # stuff
> ```
> ?
> 
> LGTM. Clear separation.
> Can I start to implement it, or are there any vetos? :)

**Comment by aboe76** [comment]
@alxwr and @0xf10e I think that will be the best solution, it's backwards compatible and even makes the data separation clearer on where parameters will be used.

**Comment by alxwr** [comment]
@0xf10e @aboe76  Well, it's `users-formula` then. Thanks for your time and effort!
I'll update the PR as soon as I'm able grab a time slot. :-)

**Comment by alxwr** [comment]
Just messed up the commits in this PR, and can't force-push. Please see #157 for a clean 5-line commit.

**Pull request closed without merging**
