### PR TITLE
Dont require vim-formula by default

### LINKED ISSUE #166: vimrc state does not work
The `vimrc` state fails.

**vimrc.sls**
```
include:
  - users
  - vim

```

**ERROR**
```
    Specified SLS vim in saltenv base is not available on the salt master or through a configured fileserver
```

### PR DESCRIPTION
**Pull request by noelmcloughlin**
- Resolve #166 formula should work as-is by default
- introduce `default.yaml`

### CODE REVIEW

**Comment by 0xf10e** [comment]
The pillar for this should be under `pillar[users-formula]` instead of `pillar[users]`.

**Comment by noelmcloughlin** [comment]
Thanks, good catch.

**Comment by aboe76** [comment]
@noelmcloughlin I get the following error after your merge:
```
[CRITICAL] Rendering SLS 'base:users' failed: Jinja variable 'defaults' is undefined
/var/cache/salt/minion/files/base/users/map.jinja(3):
---
# vim: sts=2 ts=2 sw=2 et ai

{% set users = salt['grains.filter_by'](    <======================
  defaults,
  merge=salt['grains.filter_by']({
  'MacOS': {
    'sudoers_dir': '/etc/sudoers.d',
    'sudoers_file': '/etc/sudoers',
[...]
---
local:
    Data failed to compile:
----------
    Rendering SLS 'base:users' failed: Jinja variable 'defaults' is undefined
/var/cache/salt/minion/files/base/users/map.jinja(3):
---
# vim: sts=2 ts=2 sw=2 et ai

{% set users = salt['grains.filter_by'](    <======================
  defaults,
  merge=salt['grains.filter_by']({
  'MacOS': {
    'sudoers_dir': '/etc/sudoers.d',
    'sudoers_file': '/etc/sudoers',
[...]
---
```

**Comment by aboe76** [comment]
I think the solution is to add above ```set users = ``` line
```
{% import_yaml 'users/defaults.yml' as defaults %}
```

**Pull request merged**
