### PR TITLE
Unique switch

### PR DESCRIPTION
**Pull request by t0fik**
Added support for creating non unique users and managing only sudo rules

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
Can you squash into one commit?

**Comment by t0fik** [comment]
Squashing to one commit will not have sense. These are two changes.

**Comment by noelmcloughlin** [comment]
@0xf10e please review & merge if happy

**Comment by 0xf10e** [comment]
Well, both features need to be documented before we can merge them, right @noelmcloughlin? ; )

@t0fik Could you add some bits for this to the `README.md`?

**Comment by noelmcloughlin** [comment]
Default switch behaviour could be added to `default` stanza in `map.jinja`?  And switches activated by pillar['user:xxx'].

```
'default': {
    'sudoers_dir': '/etc/sudoers.d',
    'sudoers_file': '/etc/sudoers',
    'googleauth_dir': '/etc/google_authenticator.d',
    'root_group': 'root',
    'shell': '/bin/bash',
    'visudo_shell': '/bin/bash',
    'bash_package': 'bash',
    'sudo_package': 'sudo',
    'googleauth_package': 'libpam-google-authenticator',
  },
```

**Comment by t0fik** [comment]
@noelmcloughlin Both options are boolean and does not need default values.
@0xf10e I've added options with default values and short description to pillar.example

**Comment by 0xf10e** [comment]
Looks good! :+1:

**Comment by noelmcloughlin** [comment]
thanks @t0fik @0xf10e for reviewing.

I would prefer booleans have defaults so simple condition ` {%- if  user['sudoonly'] %}` replaces more complex `{%- if 'sudoonly' in user and user['sudoonly'] %}`. But future PR could fix that. LGTM.

**Pull request merged**
