### PR TITLE
Add test vimrc generation

### PR DESCRIPTION
**Pull request by fzipi**
This PR adds tests to verify that .vimrc is being correctly generated.

Related to #213 .

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@fzipi If you permit me, I'll "hijack" this PR to merge in all of the changes we discussed in #213.  That will include some modifications to what you've provided here, to match the general structure we are using across all of our formulas.  I'll ensure the attribution for these parts will remain with you.  Is that OK with you?

**Comment by myii** [comment]
One thing I'm thinking about is limiting the `users.vimrc` state to only run for one of the instances.  I've just run this across all of the platforms (https://travis-ci.org/myii/users-formula/builds/605195734) and it adds 20-40 seconds per instance.

**Comment by fzipi** [comment]
For sure!

**Comment by myii** [comment]
@fzipi OK, here's what I'm proposing to push here to replace the current commits (due to amendments):

* https://github.com/myii/users-formula/compare/a1ef7e57d962%5E...86144befb9f9

This passes in Travis:

* https://travis-ci.org/myii/users-formula/builds/606361259

Specifically the new `vimrc` suite (which runs the `default` suite tests as well):

* https://travis-ci.org/myii/users-formula/jobs/606361261#L3843-L3865

I'll await your feedback before going forward.

**Comment by fzipi** [comment]
This adds lots of quality on top. It is perfect! Thanks again!

**Comment by myii** [comment]
@fzipi Thanks for the review.  I'm usually able to push _additional_ commits to a contributor's branch but I can't _force push_ to it, to replace the existing commits.  So which of the following appeals to you?

1. You could temporarily invite me as a collaborator to your fork of this formula, then I could force push and we could get this merged using this PR only.
1. I could add only my commits to another PR, get that merged in first and then you could adjust this PR to contain your modified commits, to be merged afterwards.
1. I could add all of the commits I linked to above (myii/users-formula@a1ef7e57d962^...86144be) in a separate PR and then we could close this PR.

**Comment by fzipi** [comment]
Sorry @myii , realised I owed you the answer! My apologies.

I would say let's close this one, and and let's create a new one with yours. So 3) :)

**Comment by myii** [comment]
Thanks @fzipi, I've created #216 with your (amended) commits included.

**Pull request closed without merging**
