### PR TITLE
Do not escape value of `enforce_password`

### LINKED ISSUE #82: `enforce_password: False` is ignored
UPDATE: I renamed the problem report.  See discussion below.  The root cause is a render error in the formula.

users-formula doesn't offer a way to set `enforce_password` to `False`, so to set an initial password for accounts managed via the formula, one must run a separate `user.present` state.  I would much prefer to do this via the formula.

### PR DESCRIPTION
**Pull request by xenophonf**
Fixes #82.

### CODE REVIEW

**Comment by puneetk** [comment]
you sure this works ;)

**Comment by xenophonf** [comment]
It's wrapped in an `if` statement, so it just needs to be `user.get('enforce_password')`.  I'll make the change shortly.

**Comment by xenophonf** [comment]
I take it back---it's wrapped in an `if`, so no default value is necessary (matches style elsewhere in the formula).

**Comment by xenophonf** [comment]
Thanks for merging this!

**Pull request merged**
