### PR TITLE
feat(semantic-release): implement for this formula

### LINKED ISSUE #203: Implement `semantic-release` for this formula
The main purpose of starting this issue is to actually prevent anyone else from spending time on this, since I've virtually completed this.  I'll be submitting a PR fairly soon, depending on some decisions that are being made in the `template-formula` over the coming days.

### PR DESCRIPTION
**Pull request by myii**
* Based on `ssf-formula` (v0.3.0)
  - https://github.com/myii/ssf-formula/pull/5
* Unable to use `pillar.example` directly for testing
  - Used it as a basis for `test/salt/pillar/default.sls`
  - Brought useful changes back to `pillar.example`
* Fix: avoid `users/googleauth.sls` for `RedHat` & `Suse`
* Close #203

### CODE REVIEW

**Comment by myii** [comment]
Strange, this repo isn't configured for Travis at all.  I've made a request on Slack so we'll have to wait for this to be activated before merging this.

CC: @gtmanfred.

**Comment by myii** [comment]
Thanks for the review @noelmcloughlin.

**Comment by myii** [comment]
@noelmcloughlin @aboe76 Travis has been enabled for this repo and the [tests pass](https://travis-ci.org/saltstack-formulas/users-formula/builds/568893660?utm_source=github_status&utm_medium=notification) -- probably not updating here properly since it was enabled _after_ this PR was created.  In any case, this is ready to be merged, if there aren't any concerns.

**Comment by noelmcloughlin** [comment]
Thanks @myii

**Comment by myii** [comment]
Thanks for the review and merge, @noelmcloughlin.

**Pull request merged**
