### PR TITLE
[users] add a prereq for createhome to handle the case of an absent s…

### LINKED ISSUE #181: createhome doesn't work when the home folder doesn't exist
For a user 

```
users:
  bob:
    home: /var/home/bob/
    createhome: True
```

The users state fails because useradd can't add a home in `/var/home/bob` since `/var/home` doesn't exist. 

The file.directory depends on the user to exist. We have a sort of chicken and egg problem.

### PR DESCRIPTION
**Pull request by arthurlogilab**
…ubfolder

Fixes #181

### CODE REVIEW

**Comment by 0xf10e** [comment]
Should be fine, as user/group/mode get set in the `file.directory` part of `users_{{ …}}_user`.

**Comment by aboe76** [comment]
@arthurlogilab this is strange, because the variable ```createhome``` does add the -m and ```home``` is defined so the command should look like ```useradd -md``` which should work

**Comment by aboe76** [comment]
@arthurlogilab was looking into the man page of useradd and found the following which isn't in the user.state of saltstack which might help: ```--base-dir```

```
-b, --base-dir BASE_DIR
           The default base directory for the system if -d HOME_DIR is not specified.  BASE_DIR is
           concatenated with the account name to define the home directory. If the -m option is not
           used, BASE_DIR must exist.

           If this option is not specified, useradd will use the base directory specified by the HOME
           variable in /etc/default/useradd, or /home by default.
```

If this could be implemented in the user module and state we could use this as an solution to your problem.

**Comment by 0xf10e** [comment]
Sounds good to me, @aboe76!
Had a quick look at [FreeBSD's `pw`](https://www.freebsd.org/cgi/man.cgi?pw) and there's a `-b` for this for `pw`'s `useradd` subcommand.
For OpenBSD's `useradd` [the manpage ](http://man.openbsd.org/useradd#b) is pretty clear about this:

> -b base-directory
>    Sets the base directory. This is the directory to which the 
> user directory is added, which will be created if the -m 
> option is specified and no -d option is specified

**Comment by aboe76** [comment]
@0xf10e created: https://github.com/saltstack/salt/issues/48591

**Comment by aboe76** [comment]
@arthurlogilab see #183

**Pull request merged**
