### PR TITLE
added dir_mode logic for users.user_files

### PR DESCRIPTION
**Pull request by sevrob**
Added logic for setting directory mode logic in users.user_files.

### CODE REVIEW

**Comment by myii** [comment]
@sevrob Thanks for this PR, I'm fine with it in general.

@aboe76 We need to consider something about `dir_mode`: it's [not supported on Windows](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.recurse).  So how about a little comment in the `pillar.example` to explain that (just above the line added)?  Ultimately, this isn't such a big problem because all the user has to do is not add this to their pillar.

However, I checked within this formula and there is a `dir_mode` problem, where it is being used without the option to unset it:

https://github.com/saltstack-formulas/users-formula/blob/8d48adb3a24318810c7a214dea02224de5293bf1/users/init.sls#L225

This one will need to be resolved, to prevent issues for Windows minions.  I don't have any to hand to see what error is displayed but we shouldn't do this in any case.

**Comment by sevrob** [comment]
new comment to pillar.example added.

**Comment by aboe76** [comment]
@sevrob can you add the fix for the dir mode here?

https://github.com/saltstack-formulas/users-formula/blob/8d48adb3a24318810c7a214dea02224de5293bf1/users/init.sls#L225

after that I'm fine with merging

**Comment by myii** [comment]
@aboe76 I've just merged this because this PR is complete for what it does and I don't want to trouble @sevrob further for something that is unrelated to this PR's changeset.  I've captured this issue under #206 instead.

Thanks for this PR, @sevrob.  If you do want to help out with #206, that would be appreciated.

**Comment by aboe76** [comment]
@myii good call, @sevrob thanks for you contributions!

**Pull request merged**
